[package]
name = "unicorn"
version = "0.3.0"
authors = ["Sébastien Duquette <ekse.0x@gmail.com>"]
description = "Rust bindings for the unicorn emulator"
repository = "https://github.com/ekse/unicorn-rs"
documentation = "http://ekse.github.io/unicorn/"
license = "GPL-2.0"
readme = "README.md"
include = ["src/*", "tests/*", "Cargo.toml", "COPYING", "README.md"]
build = "build.rs"
links = "unicorn"

[build-dependencies]
gcc = "0.3"

[dependencies]
bitflags = "0.6"
libc = "0.2.*"
